apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - image: jakobpetek/catalog-service:2023-12-14-14-11-43
          name: catalog-service
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_PORT

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_NAME

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_USERNAME

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 8080
              name: server

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3



---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: catalog-service
