apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - image: jakobpetek/catalogservice:1.0
          name: catalog-service
          env:
            - name: DATABASE_HOST
              value:
            - name: DATABASE_PORT
              value: 5432
            - name: DATABASE_NAME
              value:
            - name: DATABASE_USERNAME
              value:
            - name: DATABASE_PASSWORD
              value:
          ports:
            - containerPort: 8080
              name: server


---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: catalog-service
