apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - image: jakobpetek/inventoryservice:1.0
          name: inventory-service
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: db-catalog
                  key: DATABASE_PORT

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-inventory
                  key: DATABASE_NAME

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-inventory
                  key: DATABASE_USERNAME

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-inventory
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              name: server


---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: inventory-service
