apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - image: jakobpetek/reservation-service:2024-01-17-14-46-24
          name: reservation-service

          ports:
            - containerPort: 8082
              name: server


---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: reservation-service
