name: build with Maven and package as Docker image

on:
  push:
    paths:
      - 'catalog-service/**'
      - 'inventory-service/**'
  pull_request:
    paths:
      - 'catalog-service/**'
      - 'inventory-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            catalogservice:
              - 'catalog-service/**'
            inventoryservice:
              - 'inventory-service/**'

      # run only if 'catalogservice' files were changed
      - name: catalogservice
        if: steps.filter.outputs.catalogservice == 'true'
        run: |       
          - uses: actions/checkout@v3

          - name: Get current time
            id: current-time
            uses: josStorer/get-current-time@v2.0.2
            with:
              format: YYYY-MM-DD-HH-mm-ss
              utcOffset: "+01:00"

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v3
            with:
              file: ./Dockerfile_catalog_service
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalog-service:${{ steps.current-time.outputs.formattedTime }}

